import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

const colleges = [
  // ==================== IVY LEAGUE ====================
  {
    name: "Harvard University",
    shortName: "Harvard",
    location: "Cambridge, MA",
    state: "MA",
    type: "private",
    size: "medium",
    setting: "urban",
    avgGPA: 4.18,
    gpa25thPercentile: 4.0,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1460,
    sat75thPercentile: 1580,
    act25thPercentile: 33,
    act75thPercentile: 35,
    acceptanceRate: 3.4,
    applicationDeadlineRegular: new Date("2025-01-01"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Economics", "Computer Science", "Government", "Biology"],
    websiteUrl: "https://www.harvard.edu",
  },
  {
    name: "Yale University",
    shortName: "Yale",
    location: "New Haven, CT",
    state: "CT",
    type: "private",
    size: "medium",
    setting: "urban",
    avgGPA: 4.14,
    gpa25thPercentile: 3.95,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1460,
    sat75thPercentile: 1580,
    act25thPercentile: 33,
    act75thPercentile: 35,
    acceptanceRate: 4.5,
    applicationDeadlineRegular: new Date("2025-01-02"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Political Science", "History", "Drama", "Economics"],
    websiteUrl: "https://www.yale.edu",
  },
  {
    name: "Princeton University",
    shortName: "Princeton",
    location: "Princeton, NJ",
    state: "NJ",
    type: "private",
    size: "medium",
    setting: "suburban",
    avgGPA: 3.95,
    gpa25thPercentile: 3.9,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1450,
    sat75thPercentile: 1570,
    act25thPercentile: 33,
    act75thPercentile: 35,
    acceptanceRate: 5.6,
    applicationDeadlineRegular: new Date("2025-01-01"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Mathematics", "Physics", "Economics", "Public Policy"],
    websiteUrl: "https://www.princeton.edu",
  },
  {
    name: "Columbia University",
    shortName: "Columbia",
    location: "New York, NY",
    state: "NY",
    type: "private",
    size: "medium",
    setting: "urban",
    avgGPA: 4.15,
    gpa25thPercentile: 3.95,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1450,
    sat75thPercentile: 1560,
    act25thPercentile: 33,
    act75thPercentile: 35,
    acceptanceRate: 3.9,
    applicationDeadlineRegular: new Date("2025-01-01"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Political Science", "Economics", "Engineering", "Journalism"],
    websiteUrl: "https://www.columbia.edu",
  },
  {
    name: "University of Pennsylvania",
    shortName: "UPenn",
    location: "Philadelphia, PA",
    state: "PA",
    type: "private",
    size: "large",
    setting: "urban",
    avgGPA: 3.9,
    gpa25thPercentile: 3.85,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1440,
    sat75thPercentile: 1560,
    act25thPercentile: 33,
    act75thPercentile: 35,
    acceptanceRate: 6.5,
    applicationDeadlineRegular: new Date("2025-01-05"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Business (Wharton)", "Nursing", "Engineering", "Economics"],
    websiteUrl: "https://www.upenn.edu",
  },
  {
    name: "Brown University",
    shortName: "Brown",
    location: "Providence, RI",
    state: "RI",
    type: "private",
    size: "medium",
    setting: "urban",
    avgGPA: 4.08,
    gpa25thPercentile: 3.9,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1440,
    sat75thPercentile: 1560,
    act25thPercentile: 33,
    act75thPercentile: 35,
    acceptanceRate: 5.1,
    applicationDeadlineRegular: new Date("2025-01-03"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Computer Science", "Applied Mathematics", "Biology", "Economics"],
    websiteUrl: "https://www.brown.edu",
  },
  {
    name: "Cornell University",
    shortName: "Cornell",
    location: "Ithaca, NY",
    state: "NY",
    type: "private",
    size: "large",
    setting: "rural",
    avgGPA: 4.07,
    gpa25thPercentile: 3.8,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1400,
    sat75thPercentile: 1540,
    act25thPercentile: 32,
    act75thPercentile: 35,
    acceptanceRate: 7.3,
    applicationDeadlineRegular: new Date("2025-01-02"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Engineering", "Hotel Management", "Agriculture", "Architecture"],
    websiteUrl: "https://www.cornell.edu",
  },
  {
    name: "Dartmouth College",
    shortName: "Dartmouth",
    location: "Hanover, NH",
    state: "NH",
    type: "private",
    size: "small",
    setting: "rural",
    avgGPA: 4.11,
    gpa25thPercentile: 3.9,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1440,
    sat75thPercentile: 1560,
    act25thPercentile: 32,
    act75thPercentile: 35,
    acceptanceRate: 6.2,
    applicationDeadlineRegular: new Date("2025-01-02"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Economics", "Government", "Engineering", "Computer Science"],
    websiteUrl: "https://www.dartmouth.edu",
  },

  // ==================== TOP PRIVATE UNIVERSITIES ====================
  {
    name: "Stanford University",
    shortName: "Stanford",
    location: "Stanford, CA",
    state: "CA",
    type: "private",
    size: "large",
    setting: "suburban",
    avgGPA: 3.96,
    gpa25thPercentile: 3.9,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1440,
    sat75thPercentile: 1570,
    act25thPercentile: 32,
    act75thPercentile: 35,
    acceptanceRate: 3.7,
    applicationDeadlineRegular: new Date("2025-01-05"),
    supplementalEssaysCount: 3,
    strongPrograms: ["Computer Science", "Engineering", "Business", "Biology"],
    websiteUrl: "https://www.stanford.edu",
  },
  {
    name: "Massachusetts Institute of Technology",
    shortName: "MIT",
    location: "Cambridge, MA",
    state: "MA",
    type: "private",
    size: "medium",
    setting: "urban",
    avgGPA: 4.17,
    gpa25thPercentile: 4.0,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1500,
    sat75thPercentile: 1580,
    act25thPercentile: 34,
    act75thPercentile: 36,
    acceptanceRate: 3.2,
    applicationDeadlineRegular: new Date("2025-01-01"),
    supplementalEssaysCount: 5,
    strongPrograms: ["Engineering", "Computer Science", "Physics", "Mathematics"],
    websiteUrl: "https://www.mit.edu",
  },
  {
    name: "California Institute of Technology",
    shortName: "Caltech",
    location: "Pasadena, CA",
    state: "CA",
    type: "private",
    size: "small",
    setting: "suburban",
    avgGPA: 4.19,
    gpa25thPercentile: 4.0,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1510,
    sat75thPercentile: 1580,
    act25thPercentile: 35,
    act75thPercentile: 36,
    acceptanceRate: 3.0,
    applicationDeadlineRegular: new Date("2025-01-03"),
    supplementalEssaysCount: 4,
    strongPrograms: ["Physics", "Engineering", "Astronomy", "Chemistry"],
    websiteUrl: "https://www.caltech.edu",
  },
  {
    name: "Duke University",
    shortName: "Duke",
    location: "Durham, NC",
    state: "NC",
    type: "private",
    size: "medium",
    setting: "suburban",
    avgGPA: 4.13,
    gpa25thPercentile: 3.94,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1480,
    sat75thPercentile: 1570,
    act25thPercentile: 34,
    act75thPercentile: 35,
    acceptanceRate: 5.9,
    applicationDeadlineRegular: new Date("2025-01-02"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Biomedical Engineering", "Public Policy", "Economics", "Computer Science"],
    websiteUrl: "https://www.duke.edu",
  },
  {
    name: "Northwestern University",
    shortName: "Northwestern",
    location: "Evanston, IL",
    state: "IL",
    type: "private",
    size: "large",
    setting: "suburban",
    avgGPA: 4.1,
    gpa25thPercentile: 3.92,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1440,
    sat75thPercentile: 1550,
    act25thPercentile: 33,
    act75thPercentile: 35,
    acceptanceRate: 7.0,
    applicationDeadlineRegular: new Date("2025-01-03"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Journalism", "Engineering", "Theater", "Economics"],
    websiteUrl: "https://www.northwestern.edu",
  },
  {
    name: "University of Chicago",
    shortName: "UChicago",
    location: "Chicago, IL",
    state: "IL",
    type: "private",
    size: "medium",
    setting: "urban",
    avgGPA: 4.48,
    gpa25thPercentile: 4.0,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1500,
    sat75thPercentile: 1570,
    act25thPercentile: 34,
    act75thPercentile: 35,
    acceptanceRate: 5.4,
    applicationDeadlineRegular: new Date("2025-01-02"),
    supplementalEssaysCount: 3,
    strongPrograms: ["Economics", "Mathematics", "Physics", "Political Science"],
    websiteUrl: "https://www.uchicago.edu",
  },
  {
    name: "Johns Hopkins University",
    shortName: "JHU",
    location: "Baltimore, MD",
    state: "MD",
    type: "private",
    size: "medium",
    setting: "urban",
    avgGPA: 3.93,
    gpa25thPercentile: 3.9,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1480,
    sat75thPercentile: 1570,
    act25thPercentile: 34,
    act75thPercentile: 35,
    acceptanceRate: 7.5,
    applicationDeadlineRegular: new Date("2025-01-03"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Biomedical Engineering", "Public Health", "International Relations", "Neuroscience"],
    websiteUrl: "https://www.jhu.edu",
  },
  {
    name: "Vanderbilt University",
    shortName: "Vanderbilt",
    location: "Nashville, TN",
    state: "TN",
    type: "private",
    size: "medium",
    setting: "urban",
    avgGPA: 3.91,
    gpa25thPercentile: 3.85,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1450,
    sat75thPercentile: 1560,
    act25thPercentile: 33,
    act75thPercentile: 35,
    acceptanceRate: 6.7,
    applicationDeadlineRegular: new Date("2025-01-01"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Education", "Engineering", "Medicine", "Business"],
    websiteUrl: "https://www.vanderbilt.edu",
  },
  {
    name: "Rice University",
    shortName: "Rice",
    location: "Houston, TX",
    state: "TX",
    type: "private",
    size: "small",
    setting: "urban",
    avgGPA: 3.96,
    gpa25thPercentile: 3.9,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1470,
    sat75thPercentile: 1570,
    act25thPercentile: 34,
    act75thPercentile: 36,
    acceptanceRate: 8.7,
    applicationDeadlineRegular: new Date("2025-01-01"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Engineering", "Architecture", "Music", "Biochemistry"],
    websiteUrl: "https://www.rice.edu",
  },
  {
    name: "University of Notre Dame",
    shortName: "Notre Dame",
    location: "Notre Dame, IN",
    state: "IN",
    type: "private",
    size: "large",
    setting: "suburban",
    avgGPA: 4.06,
    gpa25thPercentile: 3.9,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1400,
    sat75thPercentile: 1550,
    act25thPercentile: 32,
    act75thPercentile: 35,
    acceptanceRate: 12.9,
    applicationDeadlineRegular: new Date("2025-01-01"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Business", "Engineering", "Architecture", "Science"],
    websiteUrl: "https://www.nd.edu",
  },

  // ==================== UNIVERSITY OF CALIFORNIA SYSTEM ====================
  {
    name: "University of California, Berkeley",
    shortName: "UC Berkeley",
    location: "Berkeley, CA",
    state: "CA",
    type: "public",
    size: "large",
    setting: "urban",
    avgGPA: 3.89,
    gpa25thPercentile: 3.85,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1310,
    sat75thPercentile: 1530,
    act25thPercentile: 29,
    act75thPercentile: 35,
    acceptanceRate: 11.4,
    applicationDeadlineRegular: new Date("2024-11-30"),
    supplementalEssaysCount: 4,
    strongPrograms: ["Computer Science", "Engineering", "Business", "Economics"],
    websiteUrl: "https://www.berkeley.edu",
  },
  {
    name: "University of California, Los Angeles",
    shortName: "UCLA",
    location: "Los Angeles, CA",
    state: "CA",
    type: "public",
    size: "large",
    setting: "urban",
    avgGPA: 3.9,
    gpa25thPercentile: 3.86,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1290,
    sat75thPercentile: 1510,
    act25thPercentile: 29,
    act75thPercentile: 34,
    acceptanceRate: 9.0,
    applicationDeadlineRegular: new Date("2024-11-30"),
    supplementalEssaysCount: 4,
    strongPrograms: ["Film", "Engineering", "Psychology", "Business Economics"],
    websiteUrl: "https://www.ucla.edu",
  },
  {
    name: "University of California, San Diego",
    shortName: "UCSD",
    location: "San Diego, CA",
    state: "CA",
    type: "public",
    size: "large",
    setting: "suburban",
    avgGPA: 4.08,
    gpa25thPercentile: 4.0,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1250,
    sat75thPercentile: 1490,
    act25thPercentile: 28,
    act75thPercentile: 34,
    acceptanceRate: 24.0,
    applicationDeadlineRegular: new Date("2024-11-30"),
    supplementalEssaysCount: 4,
    strongPrograms: ["Bioengineering", "Computer Science", "Biology", "Cognitive Science"],
    websiteUrl: "https://www.ucsd.edu",
  },
  {
    name: "University of California, Santa Barbara",
    shortName: "UCSB",
    location: "Santa Barbara, CA",
    state: "CA",
    type: "public",
    size: "large",
    setting: "suburban",
    avgGPA: 4.13,
    gpa25thPercentile: 4.0,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1230,
    sat75thPercentile: 1480,
    act25thPercentile: 27,
    act75thPercentile: 34,
    acceptanceRate: 26.0,
    applicationDeadlineRegular: new Date("2024-11-30"),
    supplementalEssaysCount: 4,
    strongPrograms: ["Physics", "Chemical Engineering", "Environmental Science", "Film Studies"],
    websiteUrl: "https://www.ucsb.edu",
  },
  {
    name: "University of California, Irvine",
    shortName: "UCI",
    location: "Irvine, CA",
    state: "CA",
    type: "public",
    size: "large",
    setting: "suburban",
    avgGPA: 4.0,
    gpa25thPercentile: 3.86,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1230,
    sat75thPercentile: 1450,
    act25thPercentile: 26,
    act75thPercentile: 33,
    acceptanceRate: 21.3,
    applicationDeadlineRegular: new Date("2024-11-30"),
    supplementalEssaysCount: 4,
    strongPrograms: ["Computer Science", "Biological Sciences", "Business", "Engineering"],
    websiteUrl: "https://www.uci.edu",
  },
  {
    name: "University of California, Davis",
    shortName: "UC Davis",
    location: "Davis, CA",
    state: "CA",
    type: "public",
    size: "large",
    setting: "suburban",
    avgGPA: 4.03,
    gpa25thPercentile: 3.92,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1190,
    sat75thPercentile: 1430,
    act25thPercentile: 26,
    act75thPercentile: 33,
    acceptanceRate: 37.3,
    applicationDeadlineRegular: new Date("2024-11-30"),
    supplementalEssaysCount: 4,
    strongPrograms: ["Veterinary Medicine", "Agriculture", "Engineering", "Biological Sciences"],
    websiteUrl: "https://www.ucdavis.edu",
  },
  {
    name: "University of California, Santa Cruz",
    shortName: "UCSC",
    location: "Santa Cruz, CA",
    state: "CA",
    type: "public",
    size: "large",
    setting: "suburban",
    avgGPA: 3.76,
    gpa25thPercentile: 3.5,
    gpa75thPercentile: 3.96,
    sat25thPercentile: 1170,
    sat75thPercentile: 1400,
    act25thPercentile: 24,
    act75thPercentile: 32,
    acceptanceRate: 47.7,
    applicationDeadlineRegular: new Date("2024-11-30"),
    supplementalEssaysCount: 4,
    strongPrograms: ["Marine Biology", "Astronomy", "Computer Science", "Environmental Studies"],
    websiteUrl: "https://www.ucsc.edu",
  },
  {
    name: "University of California, Riverside",
    shortName: "UCR",
    location: "Riverside, CA",
    state: "CA",
    type: "public",
    size: "large",
    setting: "urban",
    avgGPA: 3.83,
    gpa25thPercentile: 3.6,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1120,
    sat75thPercentile: 1350,
    act25thPercentile: 22,
    act75thPercentile: 30,
    acceptanceRate: 66.1,
    applicationDeadlineRegular: new Date("2024-11-30"),
    supplementalEssaysCount: 4,
    strongPrograms: ["Entomology", "Plant Biology", "Business", "Engineering"],
    websiteUrl: "https://www.ucr.edu",
  },
  {
    name: "University of California, Merced",
    shortName: "UC Merced",
    location: "Merced, CA",
    state: "CA",
    type: "public",
    size: "medium",
    setting: "suburban",
    avgGPA: 3.61,
    gpa25thPercentile: 3.3,
    gpa75thPercentile: 3.9,
    sat25thPercentile: 1050,
    sat75thPercentile: 1280,
    act25thPercentile: 19,
    act75thPercentile: 28,
    acceptanceRate: 89.0,
    applicationDeadlineRegular: new Date("2024-11-30"),
    supplementalEssaysCount: 4,
    strongPrograms: ["Engineering", "Biological Sciences", "Management", "Psychology"],
    websiteUrl: "https://www.ucmerced.edu",
  },

  // ==================== TOP STATE FLAGSHIPS ====================
  {
    name: "University of Michigan",
    shortName: "UMich",
    location: "Ann Arbor, MI",
    state: "MI",
    type: "public",
    size: "large",
    setting: "urban",
    avgGPA: 3.9,
    gpa25thPercentile: 3.82,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1340,
    sat75thPercentile: 1530,
    act25thPercentile: 31,
    act75thPercentile: 34,
    acceptanceRate: 17.7,
    applicationDeadlineRegular: new Date("2025-02-01"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Business (Ross)", "Engineering", "Computer Science", "Psychology"],
    websiteUrl: "https://www.umich.edu",
  },
  {
    name: "University of Virginia",
    shortName: "UVA",
    location: "Charlottesville, VA",
    state: "VA",
    type: "public",
    size: "large",
    setting: "suburban",
    avgGPA: 4.32,
    gpa25thPercentile: 4.11,
    gpa75thPercentile: 4.5,
    sat25thPercentile: 1340,
    sat75thPercentile: 1510,
    act25thPercentile: 31,
    act75thPercentile: 34,
    acceptanceRate: 19.0,
    applicationDeadlineRegular: new Date("2025-01-05"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Business (McIntire)", "Architecture", "Engineering", "Political Science"],
    websiteUrl: "https://www.virginia.edu",
  },
  {
    name: "University of North Carolina at Chapel Hill",
    shortName: "UNC",
    location: "Chapel Hill, NC",
    state: "NC",
    type: "public",
    size: "large",
    setting: "suburban",
    avgGPA: 4.39,
    gpa25thPercentile: 4.0,
    gpa75thPercentile: 4.7,
    sat25thPercentile: 1300,
    sat75thPercentile: 1480,
    act25thPercentile: 29,
    act75thPercentile: 34,
    acceptanceRate: 16.8,
    applicationDeadlineRegular: new Date("2025-01-15"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Business (Kenan-Flagler)", "Journalism", "Public Health", "Biology"],
    websiteUrl: "https://www.unc.edu",
  },
  {
    name: "University of Texas at Austin",
    shortName: "UT Austin",
    location: "Austin, TX",
    state: "TX",
    type: "public",
    size: "large",
    setting: "urban",
    avgGPA: 3.83,
    gpa25thPercentile: 3.7,
    gpa75thPercentile: 3.95,
    sat25thPercentile: 1230,
    sat75thPercentile: 1480,
    act25thPercentile: 27,
    act75thPercentile: 34,
    acceptanceRate: 31.4,
    applicationDeadlineRegular: new Date("2024-12-01"),
    supplementalEssaysCount: 3,
    strongPrograms: ["Computer Science", "Business", "Engineering", "Communication"],
    websiteUrl: "https://www.utexas.edu",
  },
  {
    name: "University of Wisconsin-Madison",
    shortName: "UW-Madison",
    location: "Madison, WI",
    state: "WI",
    type: "public",
    size: "large",
    setting: "urban",
    avgGPA: 3.88,
    gpa25thPercentile: 3.75,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1300,
    sat75thPercentile: 1470,
    act25thPercentile: 28,
    act75thPercentile: 33,
    acceptanceRate: 49.1,
    applicationDeadlineRegular: new Date("2025-02-01"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Engineering", "Business", "Biology", "Computer Science"],
    websiteUrl: "https://www.wisc.edu",
  },
  {
    name: "University of Illinois Urbana-Champaign",
    shortName: "UIUC",
    location: "Champaign, IL",
    state: "IL",
    type: "public",
    size: "large",
    setting: "suburban",
    avgGPA: 3.83,
    gpa25thPercentile: 3.68,
    gpa75thPercentile: 3.97,
    sat25thPercentile: 1340,
    sat75thPercentile: 1520,
    act25thPercentile: 29,
    act75thPercentile: 34,
    acceptanceRate: 45.1,
    applicationDeadlineRegular: new Date("2025-01-05"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Computer Science", "Engineering", "Accounting", "Psychology"],
    websiteUrl: "https://www.illinois.edu",
  },
  {
    name: "University of Washington",
    shortName: "UW",
    location: "Seattle, WA",
    state: "WA",
    type: "public",
    size: "large",
    setting: "urban",
    avgGPA: 3.8,
    gpa25thPercentile: 3.65,
    gpa75thPercentile: 3.95,
    sat25thPercentile: 1240,
    sat75thPercentile: 1470,
    act25thPercentile: 27,
    act75thPercentile: 33,
    acceptanceRate: 47.9,
    applicationDeadlineRegular: new Date("2024-11-15"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Computer Science", "Engineering", "Business", "Medicine"],
    websiteUrl: "https://www.washington.edu",
  },
  {
    name: "Georgia Institute of Technology",
    shortName: "Georgia Tech",
    location: "Atlanta, GA",
    state: "GA",
    type: "public",
    size: "large",
    setting: "urban",
    avgGPA: 4.07,
    gpa25thPercentile: 3.9,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1370,
    sat75thPercentile: 1530,
    act25thPercentile: 31,
    act75thPercentile: 35,
    acceptanceRate: 16.0,
    applicationDeadlineRegular: new Date("2025-01-01"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Engineering", "Computer Science", "Business", "Architecture"],
    websiteUrl: "https://www.gatech.edu",
  },
  {
    name: "University of Florida",
    shortName: "UF",
    location: "Gainesville, FL",
    state: "FL",
    type: "public",
    size: "large",
    setting: "suburban",
    avgGPA: 4.4,
    gpa25thPercentile: 4.3,
    gpa75thPercentile: 4.6,
    sat25thPercentile: 1290,
    sat75thPercentile: 1450,
    act25thPercentile: 28,
    act75thPercentile: 33,
    acceptanceRate: 23.0,
    applicationDeadlineRegular: new Date("2024-11-01"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Engineering", "Business", "Agriculture", "Journalism"],
    websiteUrl: "https://www.ufl.edu",
  },
  {
    name: "Ohio State University",
    shortName: "OSU",
    location: "Columbus, OH",
    state: "OH",
    type: "public",
    size: "large",
    setting: "urban",
    avgGPA: 3.83,
    gpa25thPercentile: 3.64,
    gpa75thPercentile: 3.95,
    sat25thPercentile: 1240,
    sat75thPercentile: 1450,
    act25thPercentile: 27,
    act75thPercentile: 32,
    acceptanceRate: 53.0,
    applicationDeadlineRegular: new Date("2025-02-01"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Business (Fisher)", "Engineering", "Agriculture", "Health Sciences"],
    websiteUrl: "https://www.osu.edu",
  },

  // ==================== TOP LIBERAL ARTS COLLEGES ====================
  {
    name: "Williams College",
    shortName: "Williams",
    location: "Williamstown, MA",
    state: "MA",
    type: "private",
    size: "small",
    setting: "rural",
    avgGPA: 3.95,
    gpa25thPercentile: 3.88,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1410,
    sat75thPercentile: 1560,
    act25thPercentile: 32,
    act75thPercentile: 35,
    acceptanceRate: 8.0,
    applicationDeadlineRegular: new Date("2025-01-01"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Economics", "Political Science", "Art History", "Mathematics"],
    websiteUrl: "https://www.williams.edu",
  },
  {
    name: "Amherst College",
    shortName: "Amherst",
    location: "Amherst, MA",
    state: "MA",
    type: "private",
    size: "small",
    setting: "suburban",
    avgGPA: 3.96,
    gpa25thPercentile: 3.9,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1410,
    sat75thPercentile: 1540,
    act25thPercentile: 32,
    act75thPercentile: 35,
    acceptanceRate: 7.0,
    applicationDeadlineRegular: new Date("2025-01-01"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Economics", "Political Science", "English", "Biology"],
    websiteUrl: "https://www.amherst.edu",
  },
  {
    name: "Swarthmore College",
    shortName: "Swarthmore",
    location: "Swarthmore, PA",
    state: "PA",
    type: "private",
    size: "small",
    setting: "suburban",
    avgGPA: 4.08,
    gpa25thPercentile: 3.9,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1390,
    sat75thPercentile: 1540,
    act25thPercentile: 31,
    act75thPercentile: 35,
    acceptanceRate: 6.4,
    applicationDeadlineRegular: new Date("2025-01-01"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Engineering", "Economics", "Political Science", "Biology"],
    websiteUrl: "https://www.swarthmore.edu",
  },
  {
    name: "Pomona College",
    shortName: "Pomona",
    location: "Claremont, CA",
    state: "CA",
    type: "private",
    size: "small",
    setting: "suburban",
    avgGPA: 3.95,
    gpa25thPercentile: 3.9,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1400,
    sat75thPercentile: 1540,
    act25thPercentile: 32,
    act75thPercentile: 35,
    acceptanceRate: 7.0,
    applicationDeadlineRegular: new Date("2025-01-01"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Economics", "Politics", "Neuroscience", "Computer Science"],
    websiteUrl: "https://www.pomona.edu",
  },
  {
    name: "Wellesley College",
    shortName: "Wellesley",
    location: "Wellesley, MA",
    state: "MA",
    type: "private",
    size: "small",
    setting: "suburban",
    avgGPA: 3.9,
    gpa25thPercentile: 3.8,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1370,
    sat75thPercentile: 1520,
    act25thPercentile: 31,
    act75thPercentile: 34,
    acceptanceRate: 13.6,
    applicationDeadlineRegular: new Date("2025-01-01"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Economics", "Political Science", "Biology", "Psychology"],
    websiteUrl: "https://www.wellesley.edu",
  },

  // ==================== MORE SELECTIVE UNIVERSITIES ====================
  {
    name: "Carnegie Mellon University",
    shortName: "CMU",
    location: "Pittsburgh, PA",
    state: "PA",
    type: "private",
    size: "medium",
    setting: "urban",
    avgGPA: 3.9,
    gpa25thPercentile: 3.78,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1460,
    sat75thPercentile: 1560,
    act25thPercentile: 33,
    act75thPercentile: 35,
    acceptanceRate: 11.3,
    applicationDeadlineRegular: new Date("2025-01-03"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Computer Science", "Engineering", "Drama", "Business"],
    websiteUrl: "https://www.cmu.edu",
  },
  {
    name: "Washington University in St. Louis",
    shortName: "WashU",
    location: "St. Louis, MO",
    state: "MO",
    type: "private",
    size: "medium",
    setting: "suburban",
    avgGPA: 4.16,
    gpa25thPercentile: 4.0,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1470,
    sat75thPercentile: 1560,
    act25thPercentile: 33,
    act75thPercentile: 35,
    acceptanceRate: 11.0,
    applicationDeadlineRegular: new Date("2025-01-02"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Medicine", "Business (Olin)", "Architecture", "Biology"],
    websiteUrl: "https://www.wustl.edu",
  },
  {
    name: "Emory University",
    shortName: "Emory",
    location: "Atlanta, GA",
    state: "GA",
    type: "private",
    size: "medium",
    setting: "suburban",
    avgGPA: 3.9,
    gpa25thPercentile: 3.78,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1370,
    sat75thPercentile: 1520,
    act25thPercentile: 31,
    act75thPercentile: 34,
    acceptanceRate: 11.4,
    applicationDeadlineRegular: new Date("2025-01-01"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Business", "Nursing", "Public Health", "Biology"],
    websiteUrl: "https://www.emory.edu",
  },
  {
    name: "Georgetown University",
    shortName: "Georgetown",
    location: "Washington, DC",
    state: "DC",
    type: "private",
    size: "medium",
    setting: "urban",
    avgGPA: 4.01,
    gpa25thPercentile: 3.89,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1370,
    sat75thPercentile: 1520,
    act25thPercentile: 31,
    act75thPercentile: 34,
    acceptanceRate: 12.0,
    applicationDeadlineRegular: new Date("2025-01-10"),
    supplementalEssaysCount: 1,
    strongPrograms: ["International Relations", "Political Science", "Business", "Nursing"],
    websiteUrl: "https://www.georgetown.edu",
  },
  {
    name: "University of Southern California",
    shortName: "USC",
    location: "Los Angeles, CA",
    state: "CA",
    type: "private",
    size: "large",
    setting: "urban",
    avgGPA: 3.9,
    gpa25thPercentile: 3.79,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1370,
    sat75thPercentile: 1520,
    act25thPercentile: 31,
    act75thPercentile: 34,
    acceptanceRate: 9.9,
    applicationDeadlineRegular: new Date("2025-01-15"),
    supplementalEssaysCount: 3,
    strongPrograms: ["Film (SCA)", "Business (Marshall)", "Engineering (Viterbi)", "Communication"],
    websiteUrl: "https://www.usc.edu",
  },
  {
    name: "Tufts University",
    shortName: "Tufts",
    location: "Medford, MA",
    state: "MA",
    type: "private",
    size: "medium",
    setting: "suburban",
    avgGPA: 4.04,
    gpa25thPercentile: 3.91,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1420,
    sat75thPercentile: 1540,
    act25thPercentile: 32,
    act75thPercentile: 35,
    acceptanceRate: 9.7,
    applicationDeadlineRegular: new Date("2025-01-03"),
    supplementalEssaysCount: 2,
    strongPrograms: ["International Relations", "Engineering", "Computer Science", "Biology"],
    websiteUrl: "https://www.tufts.edu",
  },
  {
    name: "New York University",
    shortName: "NYU",
    location: "New York, NY",
    state: "NY",
    type: "private",
    size: "large",
    setting: "urban",
    avgGPA: 3.69,
    gpa25thPercentile: 3.62,
    gpa75thPercentile: 3.85,
    sat25thPercentile: 1370,
    sat75thPercentile: 1510,
    act25thPercentile: 31,
    act75thPercentile: 34,
    acceptanceRate: 12.2,
    applicationDeadlineRegular: new Date("2025-01-05"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Business (Stern)", "Film (Tisch)", "Drama", "Computer Science"],
    websiteUrl: "https://www.nyu.edu",
  },
  {
    name: "Boston College",
    shortName: "BC",
    location: "Chestnut Hill, MA",
    state: "MA",
    type: "private",
    size: "medium",
    setting: "suburban",
    avgGPA: 3.96,
    gpa25thPercentile: 3.86,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1370,
    sat75thPercentile: 1500,
    act25thPercentile: 32,
    act75thPercentile: 34,
    acceptanceRate: 15.0,
    applicationDeadlineRegular: new Date("2025-01-01"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Business (Carroll)", "Nursing", "Education", "Economics"],
    websiteUrl: "https://www.bc.edu",
  },
  {
    name: "University of Rochester",
    shortName: "Rochester",
    location: "Rochester, NY",
    state: "NY",
    type: "private",
    size: "medium",
    setting: "urban",
    avgGPA: 3.8,
    gpa25thPercentile: 3.68,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1330,
    sat75thPercentile: 1500,
    act25thPercentile: 30,
    act75thPercentile: 34,
    acceptanceRate: 39.3,
    applicationDeadlineRegular: new Date("2025-01-05"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Music (Eastman)", "Engineering", "Business", "Optics"],
    websiteUrl: "https://www.rochester.edu",
  },
  {
    name: "Boston University",
    shortName: "BU",
    location: "Boston, MA",
    state: "MA",
    type: "private",
    size: "large",
    setting: "urban",
    avgGPA: 3.88,
    gpa25thPercentile: 3.75,
    gpa75thPercentile: 4.0,
    sat25thPercentile: 1350,
    sat75thPercentile: 1500,
    act25thPercentile: 31,
    act75thPercentile: 34,
    acceptanceRate: 14.4,
    applicationDeadlineRegular: new Date("2025-01-04"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Business", "Engineering", "Film & Television", "Communication"],
    websiteUrl: "https://www.bu.edu",
  },

  // ==================== MORE PUBLIC UNIVERSITIES ====================
  {
    name: "Purdue University",
    shortName: "Purdue",
    location: "West Lafayette, IN",
    state: "IN",
    type: "public",
    size: "large",
    setting: "suburban",
    avgGPA: 3.73,
    gpa25thPercentile: 3.58,
    gpa75thPercentile: 3.91,
    sat25thPercentile: 1200,
    sat75thPercentile: 1440,
    act25thPercentile: 26,
    act75thPercentile: 33,
    acceptanceRate: 52.7,
    applicationDeadlineRegular: new Date("2025-02-01"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Engineering", "Computer Science", "Aviation", "Management"],
    websiteUrl: "https://www.purdue.edu",
  },
  {
    name: "Penn State University",
    shortName: "Penn State",
    location: "University Park, PA",
    state: "PA",
    type: "public",
    size: "large",
    setting: "suburban",
    avgGPA: 3.67,
    gpa25thPercentile: 3.55,
    gpa75thPercentile: 3.85,
    sat25thPercentile: 1230,
    sat75thPercentile: 1420,
    act25thPercentile: 27,
    act75thPercentile: 32,
    acceptanceRate: 55.2,
    applicationDeadlineRegular: new Date("2024-11-30"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Engineering", "Business", "Agriculture", "Meteorology"],
    websiteUrl: "https://www.psu.edu",
  },
  {
    name: "University of Maryland, College Park",
    shortName: "UMD",
    location: "College Park, MD",
    state: "MD",
    type: "public",
    size: "large",
    setting: "suburban",
    avgGPA: 4.32,
    gpa25thPercentile: 4.15,
    gpa75thPercentile: 4.53,
    sat25thPercentile: 1300,
    sat75thPercentile: 1490,
    act25thPercentile: 30,
    act75thPercentile: 34,
    acceptanceRate: 45.0,
    applicationDeadlineRegular: new Date("2025-01-20"),
    supplementalEssaysCount: 2,
    strongPrograms: ["Computer Science", "Business", "Engineering", "Journalism"],
    websiteUrl: "https://www.umd.edu",
  },
  {
    name: "Texas A&M University",
    shortName: "Texas A&M",
    location: "College Station, TX",
    state: "TX",
    type: "public",
    size: "large",
    setting: "suburban",
    avgGPA: 3.68,
    gpa25thPercentile: 3.52,
    gpa75thPercentile: 3.89,
    sat25thPercentile: 1160,
    sat75thPercentile: 1380,
    act25thPercentile: 25,
    act75thPercentile: 32,
    acceptanceRate: 63.0,
    applicationDeadlineRegular: new Date("2024-12-01"),
    supplementalEssaysCount: 3,
    strongPrograms: ["Engineering", "Agriculture", "Business", "Veterinary Medicine"],
    websiteUrl: "https://www.tamu.edu",
  },
  {
    name: "University of Minnesota Twin Cities",
    shortName: "UMN",
    location: "Minneapolis, MN",
    state: "MN",
    type: "public",
    size: "large",
    setting: "urban",
    avgGPA: 3.8,
    gpa25thPercentile: 3.7,
    gpa75thPercentile: 3.95,
    sat25thPercentile: 1270,
    sat75thPercentile: 1480,
    act25thPercentile: 27,
    act75thPercentile: 33,
    acceptanceRate: 75.0,
    applicationDeadlineRegular: new Date("2025-01-01"),
    supplementalEssaysCount: 1,
    strongPrograms: ["Engineering", "Business", "Psychology", "Agriculture"],
    websiteUrl: "https://www.umn.edu",
  },
]

async function main() {
  console.log("🌱 Starting college seed...")

  // Clear existing colleges
  await prisma.college.deleteMany()
  console.log("🗑️  Cleared existing colleges")

  // Insert colleges
  for (const college of colleges) {
    await prisma.college.create({
      data: college,
    })
  }

  console.log(`✅ Seeded ${colleges.length} colleges`)
  console.log("\n📊 Summary:")
  console.log(`   - Ivy League: 8`)
  console.log(`   - Top Private Universities: 11`)
  console.log(`   - UC System: 9`)
  console.log(`   - Top State Flagships: 10`)
  console.log(`   - Liberal Arts Colleges: 5`)
  console.log(`   - Other Selective Universities: 10`)
  console.log(`   - More Public Universities: 5`)
  console.log(`   Total: ${colleges.length} colleges`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
